### ISSUE TITLE
Fire hydrants

### ISSUE THREAD

**Issue by aritradatta** [CityOfNewYork/nyc-geo-metadata#1]
Firstly, thank you for presenting these data-sets - this repository is an invaluable resource to anyone working on projects relating to NYC.

I am currently working on something which requires me to identify the locations of all fire-hydrants across the 5 boroughs. I went through the available data-sets but didn't find anything that I could use.

Is this public information, and if so, where can I find it?

Any help will be much appreciated.

**Comment by ekamptner** [comment]
Hi aritradatta,

DOITT doesn't maintain fire hydrant data but we are looking into seeing if this information is made public by another department (possibly DEP).

--Erika

**Comment by aritradatta** [comment]
Fantastic - thank you so much for your help.

**Comment by aritradatta** [comment]
Hi Erika - have you been able to figure out whether the fire-hydrant data can be made available?

**Comment by ekamptner** [comment]
Hi aritadatta, 

Here are hydrant and catch basin data from DEP:

Hydrants: http://nycdep.maps.arcgis.com/home/item.html?id=c17fa53803624bab89665af2057fce84

Catch Basins: http://nycdep.maps.arcgis.com/home/item.html?id=c13e31351517469c89d0a5cb689df7e6#overview

Take care,
Erika

**Comment by aritradatta** [comment]
Thank you so much!
