### ISSUE TITLE
How is the accuracy of building heights?

### ISSUE THREAD

**Issue by lauraset** [CityOfNewYork/nyc-geo-metadata#10]
Thank you for providing so wonderful datasets. But how is the accuracy of building heights? Have you conducted accuracy assessment on it?

**Comment by ekamptner** [comment]
Hi @lauraset, 

The building height information is updated through our planimetric updates every 4 years (next update will be later this year). In between those 4-year update cycles, we manually update building height information from a variety of sources: 

- Final as-built heights as shown in plan drawings posted on Department of Buildings BIS website
- EagleView Oblique imagery, direct measurements taken on photogrammetrically controlled aerial imagery
- Cyclomedia imagery, direct measurements were taken on photogrammetrically controlled terrestrial imagery (for buildings less than 60’ tall, only)

We don’t perform any accuracy assessment for the building heights we manually enter between planimetric updates, so I would advise using with caution. If you are looking for more accurate building/height information for NYC, you could use the 2017 LiDAR datasets, specifically, the highest hit model.

**Comment by lauraset** [comment]
Thank you very much. I wonder the highest hit model refers to the dataset accessed by https://gis.ny.gov/elevation/metadata/2017NYC-topobath-DSM.XML
