### ISSUE TITLE
Footprints map and MapPLUTO

### ISSUE THREAD

**Issue by LINCH8** [CityOfNewYork/nyc-geo-metadata#13]
I am trying to calculate the building coverage ratio using the Footprints map and MapPLUTO. But it appears that the polygons in these two datasets are not perfectly consistent when loaded into ArcGIS. For many buildings, a tiny proportion of them are outside the corresponding tax lots. Is this a known issue? And is there a method to deal with this?

**Comment by mattyschell** [comment]
This is a known issue @LINCH8.  Since 4 years have passed since you asked I'm going to close this issue but please follow up if you want to discuss.
