### ISSUE TITLE
Data issues on Condo table

### ISSUE THREAD

**Issue by NYCDOBConsultant** [CityOfNewYork/nyc-geo-metadata#18]
We are a NYC agency planning to use the Condo table to translate base BBLs on the Zoning Tax Lot file into billing BBLs.

Looking at the latest instance of the data, I notice the following:

1)	66 rows have no Billing BBL – I will ignore these rows
2)	1 row has no Base BBL – I will ignore this row
3)	1 row has neither Billing BBL or Base BBL – I will ignore this row
4)	12 rows (6 pairs) where the combination of Billing BBL and Base BBL repeats, with the same Condo Numbers, sometimes with different Condo Names – this is duplicate data, as far as my function is concerned
5)	41 rows (17 pairs, triples, or quads)  where the same Base BBL is associated with more than one Billing BBL – I guess I will take the lowest Billing BBL, but this is confusing

**Comment by mattyschell** [comment]
@NYCDOBConsultant we have attempted to clean up and better QA base_bbl and billing_bbl values in the building footprints.  Most of the issues you identified above have been resolved.

I'm going to close this issue but please follow up if you would like to discuss.
