### ISSUE TITLE
Update Links on Aerial Imagery Metadata

### ISSUE THREAD

**Issue by chriswhong** [CityOfNewYork/nyc-geo-metadata#2]
https://github.com/CityOfNewYork/nyc-geo-metadata/blob/master/Metadata/Metadata_AerialImagery.md

The aerial imagery metadata includes a link section that says "Coming Soon".  I would like to consume the 2016 aerials but am unable to find any documentation on how they are served.

Thanks!

**Comment by alejandromolnar** [comment]
Hi. Same here, interested in all high res aerials. I've heard that uncertain demand and download costs are a hold-up, so perhaps 'requester pays' is acceptable as an interim or definitive approach: http://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html
Thanks, A.

**Comment by ekamptner** [comment]
Hi, 

We have updated the documentation with the links to TMS documentation (https://maps.nyc.gov/tiles/) and the application (https://maps.nyc.gov/then&now/). The TMS documentation includes several examples for consuming the orthos. 

Thanks,
Erika

**Comment by alejandromolnar** [comment]
Great, thank you!
