### ISSUE TITLE
Can't access POI dataset

### ISSUE THREAD

**Issue by eejmartin** [CityOfNewYork/nyc-geo-metadata#21]
The latest change to the POI API does not allow me to access API via Socrata. When I try to download them it gives me a message that I don't have access to download. How to register so I can use this API again?
@ekamptner 

![Screenshot 2021-12-20 004854](https://user-images.githubusercontent.com/76390572/146695299-0d48057e-f904-44c9-b3f4-30ecfea15c90.jpg)

**Comment by mattyschell** [comment]
I am closing this issue since so much time has passed.  Hopefully the NYC Open Data team got you set up with access again.
