### ISSUE TITLE
Invalid geometry types in taxmap lots shapefile.

### ISSUE THREAD

**Issue by elfprince13** [CityOfNewYork/nyc-geo-metadata#5]
@kermmartian and I were working with the taxmap lots dataset using GDAL/OGR and it reported geometries of type 6, which as far as we're aware is "reserved for future use".

Is this an error in the dataset, or is there perhaps a proprietary geometry format being used?

**Comment by mattyschell** [comment]
Tidying up the issues list by closing this one. 

The Department of Finance maintains and published tax lot spatial data.
