### ISSUE TITLE
Building Footprints Link Changing

### ISSUE THREAD

**Issue by richard-mc-cherre** [CityOfNewYork/nyc-geo-metadata#7]
The download link for the building footprints data set provided by DoITT through NYC Open Data has been changing. The part of the link (which we call the `id`) is highlighted in the image below. The changes are currently breaking our current data pipeline, requiring manual updates. Is there a point of contact, or a reason for these changes? Thanks!

![Screenshot 2019-12-04 at 11 22 01 AM](https://user-images.githubusercontent.com/54250701/70160422-71460900-1688-11ea-90f9-6363716f0344.png)

![Screenshot 2019-12-04 at 11 21 16 AM](https://user-images.githubusercontent.com/54250701/70160491-95a1e580-1688-11ea-91e2-52183e370593.png)

**Comment by ekamptner** [comment]
Hi Richard,

Thanks for reaching out. Unfortunately, this is a known bug with the Socrata tool (3rd party tool serving APIs in Open Data). We are currently working with them to resolve the issue. I'll report here if there is an update.

**Comment by richard-mc-cherre** [comment]
Thanks @ekamptner - I'll stand by/see if we can build a workaround

**Comment by mattyschell** [comment]
My understanding is that this issue with NYC Open Dataset 4x4s changing has been resolved.
