### ISSUE TITLE
What is the unit of measure for attributes in the building footprints data?

### ISSUE THREAD

**Issue by agilliland** [CityOfNewYork/nyc-geo-metadata#8]
The documentation provided is great and provides a nice description of all of the attributes included, but I didn't see any indication of what units the values are in.  For example `HEIGHTROOF` and `GROUNDELEV`, are those in feet?  meters?

I'm happy to submit a PR to update the documentation to include this if that would be helpful.

**Comment by ekamptner** [comment]
Hi Allen,

The units of measurement are based on the coordinate reference system used, which for all datasets is New York State Plane Coordinates, Long Island East Zone, NAD83, US foot. All measurements in the attribute tables are in US foot.

I'll update the building footprints page to make this more clear.
